name: trident
favicon: null
layout_spectrum: 0.3055540486238897
typography_spectrum: 0.9524823853280395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.09781450987793505
  lightness: 0.7553953949827701
  saturation: 0.6428412746172398
  rhythmicContrast: 0.5683796384837478
purpose: []
