name: trident
favicon: null
layout_spectrum: 0.77744
typography_spectrum: 0.40342
title: 'The Trident - Politics, Entertainment, and Cooking'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00447f'
    - '#9fe0fe'
    - '#4e8fc5'
    - '#d7fdfd'
  brandStrength: 0
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
